### ISSUE TITLE
Status inquiry 

### ISSUE THREAD

**Issue by cheribulm** [gobo-ws/ola-trigger-wiz-light-dmx#1]
Just wanted to inquire where you might be in implementing these tasks?
Channel 3 Color temperature. Value 0-255 (2200-6500K)
Channel 4 Cold white intensity. Value 1-255
Channel 5 Warm white intensity. Value 1-255
Channel 6 Red intensity. Value 1-255
Channel 7 Green intensity. Value 1-255
Channel 8 Blue intensity. Value 1-255

I recently installed 6 par38 WIZ lights and will probably install 10 more. My goal hope is to be able to control them by a software called Lightkey [](https://lightkeyapp.com/) by using DMX and automate them by midi triggers. 

So if you need someone to test things please let me know. 

#question

**Comment by gobo-ws** [comment]
Hi @cheribulm , I don't have any roadmap but hopefully I can publish something within a few weeks, but no guarantees. 
Please send me an e-mail, hello@johan.lighting
Thanks!
